name: Build & Publish

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
      - name: Install modules
        run: yarn install --immutable
      - name: Run check-all
        run: yarn check-all

  publish-simplestorage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/simplestorage
    needs: test
    if: startsWith(github.ref, 'refs/tags/release-simplestorage-')
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
      - name: Install modules
        run: yarn install --immutable
      - name: Build
        run: yarn run build
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-browser-simplestorage:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/release-browser-simplestorage-')
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
      - name: Install modules
        run: yarn install --immutable
      - name: Build
        run: yarn run build
      - name: Publish to npm
        run: npm publish --access public
        working-directory: packages/browser-simplestorage
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-react-native-async-simplestorage:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/release-react-native-async-simplestorage-')
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
      - name: Install modules
        run: yarn install --immutable
      - name: Build
        run: yarn run build
      - name: Publish to npm
        run: npm publish --access public
        working-directory: packages/react-native-async-simplestorage
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
